buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.2.2")
    }
}

ext {
    minSdkVersion = 33
    compileSdkVersion = 34
    targetSdkVersion = 33
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
